set(CMAKE_C_COMPILER cl.exe)
set(CMAKE_CXX_COMPILER cl.exe)

set(CMAKE_CXX_FLAGS_INIT "/W4 /permissive-")

set(CMAKE_CXX_FLAGS_DEBUG           "/MTd /Zi /Od /Ob0 /RTC1 /DDEBUG")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO  "/MT /Zi /O2 /Ob1 /DDEBUG")
set(CMAKE_CXX_FLAGS_RELEASE         "/MT /O2 /Ob2 /DNDEBUG")
set(CMAKE_CXX_FLAGS_MINSIZEREL      "/MT /O1 /Ob2 /DNDEBUG")