set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)

set(CMAKE_CXX_FLAGS_INIT "-Wall -Wextra -stdlib=libc++")
set(CMAKE_CXX_LINK_FLAGS_INIT "-stdlib=libc++")

set(CMAKE_CXX_FLAGS_DEBUG           "-g -O0 -DDEBUG")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO  "-g -O2 -DDEBUG")
set(CMAKE_CXX_FLAGS_RELEASE         "-O3 -DNDEBUG")
set(CMAKE_CXX_FLAGS_MINSIZEREL      "-Os -DNDEBUG")